#!/usr/bin/env bash
echo "What's New"
echo "`git log $(git describe --abbrev=0 --tags $(git describe --abbrev=0)^)...$(git describe --abbrev=0) --pretty=format:"%s" -i -E --grep="^(\[CI\]|\[FIX\]|\[DOC\]|\[TEST\]|\[FEATURE\]|\[REVERT\]|\[FILTERADD\]|\[FILTERMOD\])"`"
#echo "`git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%s" -i -E --grep="^(\[CI\]|\[FIX\]|\[DOC\]|\[TEST\]|\[FEATURE\]|\[REVERT\]|\[FILTERADD\]|\[FILTERMOD\])"`"