site_name: test

nav:
  - Home: "index.md"
  - Getting Started:
      - "Quickstart": "gettingstarted/quickstart.md"


theme: readthedocs
markdown_extensions:
  - toc:
      permalink: True
  - smarty
  - fenced_code
  - sane_lists
  - codehilite

plugins:
    - search
    - pdf-export