#!/usr/bin/env bash


      __commitlist2="$(git log --pretty=oneline v2.0.1... | cat)"$'\n'


      __commitlist="What's New "$'\n'
      declare -a ReleaseColumn=("CI" "DOC" "FIX" "FEATURE" "FILTERADD" "FILTERMOD" "REVERT" "TEST")
      for col in ${ReleaseColumn[@]};
      do
        tag=0
        columnNotes=()
        while IFS= read -r line;
        do
          columnNotes+=( "$line" )
        done < <( (git log --pretty=oneline:"%s" -i -E --grep="^\[$col\]*" v2.0.1... |cat) )
        if [ -n "$columnNotes" ]; then
          for i in "${columnNotes[@]}"
          do
            IFS=' '
            read -ra my_array2 <<< $i
            if [[ ${my_array2[@]:1} = *[!\ ]* ]]; then
              if [ "$tag" -eq 0 ]; then
                __commitlist+="[$col]"$'\n'
                tag=1
              fi
              __commitlist+="${my_array2[@]:1}"$'\n'
            fi
          done
        fi
      done
      echo $__commitlist
     echo $__commitlist2
#
##      __commitlist="What's New "$'\n'
##      declare -a ReleaseColumn=("CI" "DOC" "FIX" "FEATURE" "FILTERADD" "FILTERMOD" "REVERT" "TEST")
##      for col in ${ReleaseColumn[@]};
##      do
##        #echo $col
##        columnNotes=()
##        while IFS= read -r line;
##        do
##          columnNotes+=( "$line" )
##        done < <( (git log --pretty=format:"%s" -i -E --grep="^(\[$col\])" v1.22.0...) )
##        #echo $columnNotes
##        if [ -n "$columnNotes" ]; then
##          #echo "here"
##          __commitlist+="[$col]"$'\n'
##          for i in "${columnNotes[@]}"
##          do
##            IFS=' '
##            read -ra my_array2 <<< $i
##            __commitlist+="${my_array2[@]:1}"$'\n'
##          done
##        fi
##      done
#      echo $__commitlist
# Declare an array of string with type
#declare -a ReleaseColumn=("CI" "DOC" "FIX" "FEATURE" "FILTERADD" "FILTERMOD" "REVERT" "TEST")
#for col in ${ReleaseColumn[@]}; do
#     __commitlist=()
#  while IFS= read -r line; do
#      __commitlist+=( "$line" )
#  done < <( (git log --pretty=format:"%s" -i -E --grep="^(\[$col\])"$finalversion...... |cat) )
#  all_ci="[$col]"$'\n'
#  for i in "${__commitlist[@]}"
#  do
#    IFS=' '
#    read -ra my_array2 <<< $i
#    all_ci+="${my_array2[1]}"$'\n'
#  done
#
#  echo $all_ci
#done
#__commitlist=()
#while IFS= read -r line; do
#    __commitlist+=( "$line" )
#done < <( (git log --pretty=format:"%s" -i -E --grep="^(\[CI\])"... |cat) )
#
#all_ci="[CI]"$'\n'
#for i in "${__commitlist[@]}"
#do
#  IFS=' '
#  read -ra my_array2 <<< $i
#  all_ci+="${my_array2[1]}"$'\n'
#done
#
#echo $all_ci